### ISSUE TITLE
Slower than mmg ?

### ISSUE THREAD

**Issue by maximerenault** [MmgTools/ParMmg#115]
I may be using it wrong but when I run ParMmg on my computer with OpenMPI on 2 cores, the software is just 10x slower than Mmg on its own. It is also slower when running it on 1, 8 or 16 cores and generally gets slower as the number of processes increases.
I am remeshing a 3 million elements mesh with this command : "mpirun -n 2 parmmg_O3 Mesh.mesh -met Met.sol -hgrad 0"

I must mention that I get this warning at runtime "## Warning: MMG5_scotchCall: fail to determine scotch version. No renumbering." and failed to find a way to treat it.

**Comment by Algiane** [comment]
Hi,

The main objective or ParMmg is to allow to remesh meshes that are too large to be stored in the memory of a single compute node and it targets large architectures, not personnal computers. Even if we hope to save time when the number of MPI processes is sufficiently large, it is not our first target (and for now we haven't found the time and ressources to work on the software scalability).

It relies on an iterative remeshing-repartitioning algorithm (see https://github.com/MmgTools/ParMmg/wiki/Outline-of-the-algorithm for an overview) that calls Mmg multiple times (a strict minimum of 3 iterations are needed to ensure that the entire mesh as been remeshed but a larger number is often needed) and, comparing to Mmg, it adds an extra layer of data, computations and MPI communications to exchange informations between the partitions and maintain the mesh consistency. In consequence, it is not expected to have better performances than Mmg under ~8 MPI processes.

I attach a curve of the weak scalability of ParMmg for the uniform refinment of a sphere:
  - on 2 procs, the initial mesh contains 37k tetra and the final one 15 millions tetrahedra
  - on 1024 procs, the initial mesh contains 20 millions tetrahedra and the final one has 9G tetrahedra
  - both runs last less than 15 mins
<img width="549" alt="Capture d’écran 2024-07-22 à 18 30 35" src="https://github.com/user-attachments/assets/a5843178-08ba-4d8d-af03-8c047d07e6a8">

To get better performances, you can:
  - test the `develop` branch instead of the `master` one (we will release a new version of the software soon);
  - ensure that the number of MPI processes you ask is not too large for your mesh: as the interfaces between the partitions are freezed (== not remeshed), a too large number of partitions slows down the convergency.
  - simply use Mmg for remeshing that takes less than ~30 minutes: the software performance and computational time depend not only on the mesh size but also on the target mesh size and the work that has to be done (for example, splitting is easier and faster than collapsing).

Few remarks:
  - a 0 value is not suitable for the gradation parameter (`-hgrad`): a value strictly greater than 1 is expected. This threshold is the authorized ratio between the sizes of two connected edges. It controls the size variation and element deformation 
  - the warning about scotch is harmless and will not change the comparative behaviour of the software: scotch may fasten the Mmg calls by reducing cache misses so enabling it will fasten both Mmg and ParMmg (as ParMmg calls Mmg)
  - please, keep in mind that ParMmg is a research and open-source project: do not hesitate to contribute and improve it ;-). 
  
 Best
