### ISSUE TITLE
Error when using a single MPI process

### ISSUE THREAD

**Issue by prj-** [MmgTools/ParMmg#7]
It seems the distributed interface cannot handle mesh distributed on a single MPI process.
I end up with the following trace followed by a segmentation fault:
```
  -- PMMG: CHECK INPUT DATA
  -- CHECK INPUT DATA COMPLETED.     0.000s

  -- PHASE 1 : ANALYSIS
   -- PHASE 1 COMPLETED.     0.000s
 ## Error: PMMG_preprocessMesh_distributed: parallel interface nodes must be set through the API interface

  -- PHASE 2 : ISOTROPIC MESHING
```
but I indeed call `PMMG_Set_numberOfNodeCommunicators(mesh, 0);`
How about nonconnected meshes where each component resides in a single MPI process, and thus `PMMG_Set_numberOfNodeCommunicators(mesh, 0);` as well on all processes?

**Comment by lcirrott** [comment]
Yes, the problem with the distributed case on 1 process should be fixed in f960a89, thanks.
Regarding the nonconnected meshes:

- We explicitly enforce connected parallel partitions during partitioning. 
- If the geometrical domain is nonconnected and there is at least one partition for each subdomain, I don't see a theoretical reason preventing the algorithm from working. Anyway, I have never tested it as it was not in our envisaged applications, and it could require some minor fixes to work.
If it is a requested feature, we can further talk about your needs (are there a lot of non connected parts? Do they require parallel remeshing inside each of them?) to see how it can be done.

**Comment by prj-** [comment]
This is not a requested feature. Could you please merge `master` into `develop`, or rebase `develop` (this is the branch I'm tracking), so that we can close the issue? Or would you recommend I use `master`?

**Comment by lcirrott** [comment]
Hello,
It's done.
I definitely recommend developers to use the `develop` branch, as it contains stable updates not already packed into a release in `master` (we are sticking to the git-flow branching model https://nvie.com/posts/a-successful-git-branching-model/).
Cheers,
Luca
